version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Busingen
    volumes:
      - homeassistant_config:/config
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "3"

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

volumes:
  homeassistant_config:
