# apply the secret: kubectl apply -f mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: # echo -n 'YOUR_PASSWORD' | base64
  mongo-root-username: WUVBRF9VU0VSTkFNRQ==  # placeholder: YOUR_USERNAME
  mongo-root-password: WUVBRF9QQVNTV09SRA==  # placeholder: YOUR_PASSWORD
